apiVersion: v1
kind: Service
metadata:
  name: {{ template "distribution.fullname" . }}-redis
  labels:
    app: {{ template "distribution.name" . }}
    chart: {{ template "distribution.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  clusterIP: None
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app: {{ template "redis.name" . }}
    release: "{{ .Release.Name }}"
    role: master
